[package]
name = "ctranslate2bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
sentencepiece = { git = "https://github.com/nikita-skobov/sentencepiece" }
